export { default as isBornCertificatePass } from './isBornCertificatePass';
export { default as isForeigner } from './isForeigner';
export { default as isHKMacaoIdCard } from './isHKMacaoIdCard';
export { default as isHKMacaoPass } from './isHKMacaoPass';
export { default as isIdCard } from './isIdCard';
export { default as isPassport } from './isPassport';
export { default as isTWIdCard } from './isTWIdCard';
export { default as isTWPass } from './isTWPass';
export { default as isAll } from './isAll';
